# Generated by Django 5.0.6 on 2024-05-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_api", "0005_note_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="body",
            field=models.CharField(max_length=500),
        ),
    ]
